// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-locations.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_locations_default = defineTool({
  name: "list_locations",
  title: "List venue locations",
  description: "List all active Kediaman venue locations with their address, contact info, and facilities.",
  inputSchema: {
    include_coming_soon: z.boolean().optional().describe("Whether to include venues marked as coming soon. Defaults to false.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_coming_soon }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("locations").select("id, name, address, phone, email, category, facilities, is_coming_soon").eq("is_active", true).order("sort_order");
    if (!include_coming_soon) query = query.eq("is_coming_soon", false);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { locations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-programs.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_programs_default = defineTool2({
  name: "list_programs",
  title: "List programs and special offers",
  description: "List active programs / promotional offers (Promosi) available at Kediaman venues.",
  inputSchema: {
    category: z2.string().optional().describe("Optional category filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser2(ctx).from("programs").select("id, name, description, category, is_active").eq("is_active", true).order("sort_order");
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { programs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-articles.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_articles_default = defineTool3({
  name: "list_articles",
  title: "List published articles",
  description: "List published blog articles (Artikel) with title, slug, category, and excerpt.",
  inputSchema: {
    limit: z3.number().int().optional().describe("Max number of articles to return. Server clamps to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const capped = Math.min(Math.max(limit ?? 20, 1), 50);
    const { data, error } = await supabaseForUser3(ctx).from("articles").select("id, title, slug, category, excerpt, published_at").eq("is_published", true).order("published_at", { ascending: false }).limit(capped);
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/my-bookings.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.91.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var my_bookings_default = defineTool4({
  name: "my_bookings",
  title: "My ballroom bookings",
  description: "List ballroom booking requests belonging to the signed-in user. RLS restricts results to the caller's own rows.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("ballroom_bookings").select(
      "id, location_id, booking_date, start_time, end_time, event_name, event_type, guest_count, status, created_at"
    ).order("created_at", { ascending: false });
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wlytcvpmajllepgsqmpx";
var mcp_default = defineMcp({
  name: "kediaman-mcp",
  title: "Kediaman Corp MCP",
  version: "0.1.0",
  instructions: "Tools for Kediaman Corp \u2014 venue operator in Indonesia. Use `list_locations` for venue details, `list_programs` for special offers/Promosi, `list_articles` for blog content, and `my_bookings` to fetch the signed-in user's ballroom booking requests.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_locations_default, list_programs_default, list_articles_default, my_bookings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
